#!/usr/bin/python3

import os, sys, re, platform
from datetime import datetime

FIRST_COLUMNS = ['No.', 'Theory']
METADATA_COLUMNS = ['Rules', 'LoC', 'Time']#, 'Theory file', 'Proof file']

#html
NA_HTML = '-'

#latex
VERIFIED_TEX = '\\verified{}'
FALSIFIED_TEX = '\\falsified{}'
NA_TEX = '--'
'''
LATEX_SYNTAX = {
	'_': '\\_',
	' & ': '&nbsp&&nbsp',
	'<br />': '<br/>'
}
'''
LATEX_SYNTAX = {
	'\\newcommand': '<span style="color: brown;">\\newcommand</span>',
	'\\begin': '<span style="color: darkgreen; font-weight: bold;">\\begin</span>',
	'\\end': '<span style="color: darkgreen; font-weight: bold;">\\end</span>',
	#'{tabular}': '{<span style="color: darkslategray;">tabular</span>}',
	'\\bfseries': '<span style="color: brown;">\\bfseries</span>',
	'&': '<span style="color: blue;">&</span>',
	'\\hline': '<span style="color: brown;">\\hline</span>',
	'\\\\': '<span style="color: brown;">\\\\</span>',
	'$': '<span style="color: brown;">$</span>',
	'^': '<span style="color: brown;">^</span>',
	'_': '<span style="opacity: .2; font-size: .01rem;">\\</span>_',
}

#regexes
THEORY_REGEX = r'^theory (\w+) begin$'
WARNING_REGEX = r'^\s*WARNING\: (\d+ wellformedness check failed)\!$'
LEMMA_REGEX = r'^\s*(\w+) \((all-traces|exists-trace)\): (.+ \(\d+ steps\))$'
RULE_HEADER_REGEX = r'^rule \(modulo E\) (\w+)\:$'
RULE_HEADER_SPTHY_REGEX = r'^rule (\w+)\:$'
STEPS_REGEX = r'( - found trace| - no trace found)? \(\d+ steps\)'
TIME_REGEX = r'^real\s([\dmsh\.\,]+)$'
GNU_TIME_REGEX = r'^.*\s([\d\:\.\,]+)elapsed.*$'
TAMARIN_TIME_REGEX = r'^\s+processing time:\s([\d\:\.\,]+).*$'


MAP_COLUMNS= {"secret_key":"sk", "aliveness":"alive", "weak_agreement":"wAgree", "noninjectiveagreement":"nonInjAgree" }
def rename_column(column_i):
	if column_i.endswith('_A') or column_i.endswith('_B'):
		return MAP_COLUMNS[column_i[:-2]]+column_i[-2:]  # Remove '_A' or '_B'
	else:
		return column_i
			


# def sort_columns(columns):
# 	static_columns = []
# 	grouped_columns = []
	
# 	for col in columns:
# 		if col.endswith('_A') or col.endswith('_B'):
# 			base_name = col[:-2]  # Remove '_A' or '_B'
# 			if base_name not in grouped_columns:
# 				grouped_columns.append(base_name)
# 		else:
# 			static_columns.append(col)
# 	# Sort each group: `_A` first, then `_B`
# 	sorted_grouped_columns = [i+'_A' for i in grouped_columns]
# 	sorted_grouped_columns += [i+'_B' for i in grouped_columns]

# 	# print(sorted_grouped_columns)


# 	# for base in sorted(grouped_columns):  # Sort by base names
# 	# 	sorted_grouped_columns.extend(sorted(grouped_columns[base], key=lambda x: x.endswith('_B')))

#     # Combine static columns and sorted grouped columns
#     # Assume static columns are in the order before and after grouped columns
# 	return static_columns[:4] + sorted_grouped_columns + static_columns[4:]

def to_timeformat(time):
	hours = int(time / 3600)
	time -= hours * 3600
	mins = int(time / 60)
	time  -= mins * 60
	secs = time

	decimals_for_secs = '0'
	if hours + mins == 0:
		decimals_for_secs = '2'

	if mins + hours > 0:
		if hours > 0:
			tt = str(hours) + 'h'\
						+ '{:02d}'.format(mins) + 'm'\
						+ ('{0:02.'+ decimals_for_secs + 'f}').format(secs) + 's'
		else:
			tt = str(mins) + 'm' + ('{0:02.'+ decimals_for_secs + 'f}').format(secs) + 's'
	else:
		tt = ('{0:.'+ decimals_for_secs + 'f}').format(secs) + 's'
	
	return tt

def to_secs(time):
	t = 0.0
	if 'h' in time:
		t += int(time.split('h')[0]) * 3600
		time = time.split('h')[1]
	if 'm' in time:
		t += int(time.split('m')[0]) * 60
		time = time.split('m')[1]
	t += float(time.split('s')[0])
	return t


def _theory_name_from_spthy(spthy_path):
	"""Theory line in .spthy may be 'theory Name' with begin on the next lines."""
	with open(spthy_path, encoding='utf-8', errors='replace') as f:
		for line in f:
			line = line.strip()
			if not line or line.startswith('//'):
				continue
			m = re.match(r'^theory (\w+) begin$', line)
			if m:
				return m.group(1)
			m = re.match(r'^theory (\w+)$', line)
			if m:
				return m.group(1)
	return os.path.basename(spthy_path).replace('.spthy', '')


def _stub_results_from_spthy(spthy_path, proto_count, rules_min, rules_max, rules_sum, loc_min, loc_max, loc_sum):
	lines = open(spthy_path, encoding='utf-8', errors='replace').readlines()
	theory_name = _theory_name_from_spthy(spthy_path)
	rule_names = []
	for line in lines:
		m = re.match(RULE_HEADER_SPTHY_REGEX, line)
		if m:
			rule_names.append(m.group(1))
	num_rules = len(rule_names)
	if num_rules < rules_min:
		rules_min = num_rules
	if num_rules > rules_max:
		rules_max = num_rules
	rules_sum += num_rules
	loc = len(lines)
	if loc < loc_min:
		loc_min = loc
	if loc > loc_max:
		loc_max = loc
	loc_sum += loc
	return {
		'No.': str(proto_count),
		'Verified': 'No',
		'Theory': theory_name,
		'Theory file': spthy_path,
		'Proof file': '(missing)',
		'Rules': str(num_rules),
		'LoC': str(loc),
		'Time': NA_HTML,
	}, rules_min, rules_max, rules_sum, loc_min, loc_max, loc_sum


def create_html_code(directories, columns, tex_add):

	print('Starting collecting results...')

	global_results = []
	cols = [col for col in FIRST_COLUMNS]
	

	rules_min = 100000000
	rules_max = -1
	rules_sum = 0

	loc_min = 100000000
	loc_max = -1
	loc_sum = 0

	time_sum = 0.0
	time_min = 1000000000.0
	time_max = 0.0

	proto_count = 0
	time_row_count = 0
	missing_proof_count = 0
	spthy_files = []
	for dir in directories:
		dir_abs = os.path.abspath(dir.rstrip('/'))
		if not os.path.isdir(dir_abs):
			print('[Error] Not a directory: "%s"' % dir_abs)
			return None
		try:
			spthy_files += [
				os.path.join(dir_abs, file)
				for file in os.listdir(dir_abs)
				if file.endswith('.spthy')
			]
		except OSError as e:
			print('[Error] Cannot read directory "%s": %s' % (dir_abs, e))
			return None

	spthy_files.sort()
	spthy_files.reverse()

	for spthy_path in spthy_files:
		proto_count += 1
		proof_path = os.path.splitext(spthy_path)[0] + '.proof'
		theory_file = spthy_path
		if not os.path.isfile(proof_path):
			missing_proof_count += 1
			results, rules_min, rules_max, rules_sum, loc_min, loc_max, loc_sum = _stub_results_from_spthy(
				spthy_path, proto_count, rules_min, rules_max, rules_sum, loc_min, loc_max, loc_sum
			)
			print('No proof file for "%s" (row still listed)' % os.path.basename(spthy_path))
			global_results.append(results)
			continue

		proof_file = proof_path
		print('Parsing "%s"' % proof_file)

		results = {}
		results['Theory file'] = theory_file
		results['Proof file'] = proof_file

		results['No.'] = str(proto_count)
		results['Verified'] = 'Yes'
		
		lines = open(proof_file).readlines()
		theory_name = None
		for line in lines:
			col = None
			
			if not theory_name:
				m = re.match(THEORY_REGEX, line)
				if m: (col, result) = ('Theory', m.group(1))
			
			if not col:
				m = re.match(WARNING_REGEX, line)
				if m: (col, result) = ('WARNING', m.group(1))
			
			if not col:
				m = re.match(LEMMA_REGEX, line)
				if m: (col, result) = m.group(1,3)				

			if col:
				res = results[ col ] = result.strip()
				if col not in cols:
					cols.append(col)
				if (columns == 'all' or col in columns) and res.startswith('falsified'):
					results['Verified'] = 'No'
					graph_dir = proof_file[:-6] + '_graphs/'
					graph_path = graph_dir + col + '.pdf'
					trace_path = graph_dir + col + '.proof_trace'
					if os.path.exists(graph_path):
						results[col + '_graph'] = graph_path
					if os.path.exists(trace_path):
						results[col + '_proof_trace'] = trace_path

		

		#rules
		rule_names = []
		for line in lines:
			m = re.match(RULE_HEADER_REGEX, line)
			if m: rule_names.append(m.group(1))
		
		num_rules = len(rule_names)
		if num_rules < rules_min: rules_min = num_rules
		if num_rules > rules_max: rules_max = num_rules			
		rules_sum += num_rules
		results['Rules'] = str(num_rules)

		if os.path.exists(theory_file):
			#inspect the spthy file for diff in rule names
			for line in open(theory_file).readlines():
				m = re.match(RULE_HEADER_SPTHY_REGEX, line)
				if m and m.group(1) not in rule_names:
					print('[Warning] Rule "%s" occurs in "%s.spthy" but not in "%s.proof"'\
								% (m.group(1), proof_file, theory_file))
			#lines of code
			loc = len(open(theory_file).readlines())
			if loc < loc_min: loc_min = loc
			if loc > loc_max: loc_max = loc
			loc_sum  += loc
			results['LoC'] = str(loc)
		else:
			print('[Warning] File "%s" exists but not "%s"'\
						% (proof_file, theory_file))

		#timings
		time_display = None
		for line in lines:
			res = re.match(TIME_REGEX, line)
			if res:
				t = res.group(1)
				t = to_secs (t)					
				time_display = to_timeformat(t)
				time_sum += t
				if t < time_min: time_min = t
				if t > time_max: time_max = t
			else:
				#try to parse GNU time format
				res = re.match(GNU_TIME_REGEX, line)
				if res:
					t = res.group(1).replace(':', 'h')
					i = t.rfind('h')
					t = to_secs (t[:i]+ 'm' + t[i+1:] + 's')					
					time_display = to_timeformat(t)
					time_sum += t
					if t < time_min: time_min = t
					if t > time_max: time_max = t
				else:
					#try to parse Tamarin-produced time format
					res = re.match(TAMARIN_TIME_REGEX, line)
					if res:
						t = res.group(1)
						t = to_secs (t)					
						time_display = to_timeformat(t)
						time_sum += t
						if t < time_min: time_min = t
						if t > time_max: time_max = t

		if time_display:
			results['Time'] = time_display
			time_row_count += 1

		global_results.append(results)

	print(cols)
	#we're done collecting the data ==================================

	#check that the result of lemma x matches that of lemma x_minimal
	for results in global_results:
		if results.get('Proof file') == '(missing)':
			continue
		x_group = {}
		for (col, res) in results.items():
			key = col.replace('_minimal', '')
			res = re.sub(STEPS_REGEX, '', res)				
			if key not in x_group:
				x_group[key] = set()
			x_group[key].add(res)
		
		differ = [k for (k,v) in x_group.items() if len(v) > 1]
		for col in differ:
			proof_file = results['Proof file']
			print('[Warning] The results for "%s" and "%s_minimal" differ in "%s"'\
						% (col, col, proof_file))
	
	#add metadata
	cols = cols + METADATA_COLUMNS
	# Sort the columns list
	# print("BEFORE --------- ",cols)
	# cols = sort_columns(cols)
	# print("AFTER --------- ",cols)

	#reset cols to the columns parameter
	if columns != 'all': cols = columns

	#HTML code ==============================================
	html = 	'<!DOCTYPE html>\n<html>\n\n<head>\n<style>\n'\
					+ '/* CSS */\n'\
					+ 'body {\n'\
					+ '	font-size: .9em;\n'\
					+ '	margin: .8em;\n'\
					+ '	font-family: arial, sans-serif;\n'\
					+ '}\n'\
					+ 'table {\n'\
					+ '	border-collapse: collapse;\n'\
					+ '}\n'\
					+ 'td, th {\n'\
					+ '	text-align: left;\n'\
					+ '	padding: 10px;\n'\
					+ '}\n'\
					+ 'th {\n'\
					+ '	background-color: #2471A3;\n'\
					+ '	color: white;\n'\
					+ '	font-weight: normal;\n'\
					+ '}\n'\
					+ 'tr:nth-child(odd) {\n'\
					+ '	background-color: #F2F2F2;\n'\
					+ '}\n'\
					+ 'tr:hover {\n'\
					+ '	background-color: #D6EAF8;\n'\
					+ '}\n'\
					+ '.summary {\n'\
					+ '	line-height: 1.2em;\n'\
					+ '}\n'\
					+ '.verified {\n'\
					+ '	font-weight: bold;\n'\
					+ '}\n'\
					+ '.green {\n'\
					+ '	color: green;\n'\
					+ '}\n'\
					+ '.red {\n'\
					+ '	color: red;\n'\
					+ '}\n'\
					+ '.x-scrollable {\n'\
					+ '	overflow-x: auto;\n'\
					+ '	white-space: nowrap;\n'\
					+ '}\n'\
					+ '.latex-code {\n'\
					+ '	padding: .5em;\n'\
					+ '	font-family: Consolas, "courier new";\n'\
					+ '	background-color: #F2F2F2;\n}\n'\
					+ '</style>\n</head>\n\n'

	html += '<body>\n\n'
	html += '<h2>Analysis results</h2>\n'
	if missing_proof_count:
		html += (
			'<p class="red" style="margin: 0.5em 0 1em 0;"><b>Incomplete run:</b> '
			+ str(missing_proof_count)
			+ ' of '
			+ str(proto_count)
			+ ' theories have no <code>.proof</code> file yet (lemma columns show &ldquo;-&rdquo;). '
			+ 'Run the Tamarin batch (e.g. <code>make docker-gen-proofs</code> or '
			+ '<code>./tools/gen_proofs</code> in Docker) until every theory is proved; '
			+ 'existing <code>.proof</code> files are skipped automatically.</p>\n'
		)
	html += '\n<div class="x-scrollable">\n<table>\n'	
	
	#table head
	html += '<tr>' + ''.join(['<th>' + col + '</th>' for col in cols]) + '</tr>\n'	
	
	#start building latex code
	tex = '\\newcommand{' + FALSIFIED_TEX.replace('{}', '') + '}{falsified}<br />\n'\
				+ '\\newcommand{' + VERIFIED_TEX.replace('{}', '') + '}{verified}<br /><br />\n'\
				+ '\\begin{tabular}{ ' + 'l '*len(cols) +'}<br />\n\\hline<br />\n'\
				+ ' & '.join(['\\bfseries ' + rename_column(col) for col in cols]) + '\\\\<br />\\hline<br />\n'
	
	#fill the two tables with results for cols only
	verified_count = 0
	for results in global_results:
		html_row_data = []
		latex_row_data = []
		
		for col in cols:
			html_res = NA_HTML
			latex_res = NA_TEX
			if col in results and not results[col].startswith('analysis incomplete'):
				html_res = results[col]
				latex_res = results[col]
			
			#format html code
			if col in ['Theory file', 'Proof file']:
				html_res = '<td><a href="'+ html_res +'">'\
										+ os.path.basename(html_res) + '</a></td>'
			else:
				'''
				if col == 'Theory':
					if 'Theory file' in results or 'Proof file' in results:
						html_res += '<sup style="font-weight: normal">['
						if 'Theory file' in results:
							html_res += '<a href="' + results['Theory file'] + '">.spthy</a>'
						if 'Theory file' in results and 'Proof file' in results:
							html_res += ', '
						if 'Proof file' in results:
							html_res += '<a href="' + results['Proof file'] + '">.proof</a>'
						html_res += ']</sup>'
				'''
				_class = ''
				if col == 'Theory' and results['Verified'] == 'Yes':
					_class = ' class="verified"'
					verified_count += 1
				elif html_res.startswith('falsified'):
					_class = ' class="red"'
					pdf = results.get(col + '_graph')
					tr = results.get(col + '_proof_trace')
					if pdf and tr:
						html_res = (
							'<a href="' + pdf + '">' + html_res + ' [pdf]</a>'
							+ ' [<a href="' + tr + '">trace</a>]'
						)
					elif pdf:
						html_res = '<a href="' + pdf + '">' + html_res + ' [graph]</a>'
					elif tr:
						html_res = '<a href="' + tr + '">' + html_res + ' [trace]</a>'
				elif html_res.startswith('verified'):
					_class = ' class="green"'
				html_res = '<td' + _class + '>' + html_res + '</td>'

			html_row_data.append(html_res)
				
			#format latex code
			latex_res = re.sub(STEPS_REGEX, '', latex_res)
			latex_res = latex_res.replace('verified', VERIFIED_TEX)
			latex_res = latex_res.replace('falsified', FALSIFIED_TEX)
			if col == 'Theory' and results['Verified'] == 'Yes':
				latex_res = '\\bfseries ' + latex_res
			#add latex annotations
			if results['Theory'] in tex_add and col in tex_add[results['Theory']]:
				latex_res += tex_add[results['Theory']][col]
			
			latex_row_data.append(latex_res)
			
		html += '<tr>' + ''.join(html_row_data) + '</tr>\n'
		#tex += '&nbsp&&nbsp'.join(latex_row_data) + '\\\\<br />\n'
		tex += ' & '.join(latex_row_data) + '\\\\<br />\n'

	html += '</table>\n</div>\n\n'



	# # Add total row to LaTeX
	# total_row = ['\\textbf{Total}', '\\textbf{(\\# steps)}']  # first two cols

	# # Step columns: all columns except first 2 and last 3
	# step_cols = cols[2:-3]
	# for col in step_cols:
	# 	total = 0
	# 	for r in global_results:
	# 		if col in r:
	# 			match = re.search(r'(\d+)\s+steps', r[col])
	# 			if match:
	# 				total += int(match.group(1))
	# 	total_row.append(f'\\textbf{{{total} steps}}')

	# # Append sums of Rules, LoC, and Time
	# total_row.append(f'\\textbf{{{rules_sum}}}')
	# total_row.append(f'\\textbf{{{loc_sum}}}')
	# total_row.append(f'\\textbf{{{to_timeformat(time_sum)}}}')

	# # Add to tex
	# tex += ' & '.join(total_row) + '\\\\<br />\n\\hline<br />\n'

	tex += '\\hline<br />\n\\end{tabular}<br />\n'
	
	#summary ===============================================
	html += '<h2>Summary</h2>\n\n<div class="summary">\n'\
					+ '<p><b>Protocols: </b> '\
					+ 'total ' + str(proto_count) + ', '\
					+ 'verified ' + str(verified_count)
	if missing_proof_count:
		html += ', <b>missing proofs</b> ' + str(missing_proof_count)
	html += '</p>\n'
	
	if proto_count != 0:
		if 'Rules' in cols:
			ave = (0.0+rules_sum)/proto_count
			html += '<p><b>Number of rules:</b> '\
							+ "min " + str(rules_min) + ', '\
							+ "ave " + str(int(ave)) + ', '\
							+ "max " + str(rules_max) + '</p>\n'
		
		if 'LoC' in cols and loc_sum != 0:
			ave = (0.0+loc_sum)/proto_count
			html += '<p><b>Lines of code:</b> '\
						+ "min " + str(loc_min) + ', '\
						+ "ave " + str(int(ave)) + ', '\
						+ "max " + str(loc_max) + '</p>\n'
		
		if 'Time' in cols:
			if time_row_count == 0:
				html += '<p><b>Time:</b> no proof timings recorded</p>\n'
			else:
				ave = time_sum / time_row_count
				html += '<p><b>Time:</b> '\
								+ "min " + to_timeformat(time_min) + ', '\
								+ "ave " + to_timeformat(ave) + ', '\
								+ "max " + to_timeformat(time_max) + ', '\
								+ "sum " + to_timeformat(time_sum) + ' (' + str(time_row_count) + ' proofs with timing)</p>\n'
	
	#html += '<p><b>System info:</b> " + str(platform.uname()) + '</p>'
	#html += '<p><b>Folder(s):</b> ' + ', '.join(directories) + '</p>'
	#html += '<p><b>Report generated on:</b> '\
	#				+ datetime.now().strftime("%Y-%m-%d %H:%M:%S") + '</p>'					
	html += '</div>\n\n'

		
	#latex code ========================================
	html += '<h2>Latex code</h2>\n\n<div class="latex-code x-scrollable">\n'
	for (plain, rich) in LATEX_SYNTAX.items():
		tex = tex.replace(plain, rich)
	html += tex +'</div>\n\n</body>\n</html>'
	
	return html



def main(args):
	#defaults
	directories = set()
	columns = 'all'
	output = 'generated_results.html'
	tex_add = {}
	
	for arg in args:
		
		if arg.startswith('--columns='):
			file = arg.split('=',1)[1]
			try:
				columns = []
				for l in open(file).readlines():
					if '#' in l: l = l.split('#',1)[0]
					l = l.strip()
					if l != '': columns.append(l)
	
				if 'Theory' not in columns:
					print('[Error] No "Theory" column found in "%s"' % file)
					return
			except Exception as e:
				print('[Warning] Something is wrong with the columns file "'\
							+ file + '", so I will ignore')
				print(e)
				columns = 'all'
				
		elif arg.startswith('--output='):
			output = arg.split('=',1)[1]
		
		elif arg.startswith('--tex-add='):
			file = arg.split('=',1)[1]
			try:
				for line in open(file).readlines():
					if line.strip() == '' or line.startswith('#'):
						continue
					(proto, lemma, add) = line.split(' ',2)
					if proto not in tex_add:
						tex_add[proto] = {}					
					if lemma not in tex_add[proto]:
						tex_add[proto][lemma] = {}
					tex_add[proto][lemma] = add[:-1]
			except Exception as e:
				print('[Warning] Something is wrong with the tex-add file "'\
							+ file + '", so I will ignore')
				print(e)
				tex_add = {}
		
		else:
			directories.add(arg)

	if len(directories) == 0:
		directories = ['./']

	# print(directories, columns, tex_add)
	html = create_html_code(directories, columns, tex_add)
	
	if html:
		print('Writing output to "%s"' % output)
		outfile = open(output, 'w')
		outfile.write(html)
		outfile.close()
		print('Done.')

if __name__ == "__main__":
	main(sys.argv[1:])

